import Head from "next/head"
import OutputArea from "~/components/output-area"
import { ScrollAreaHorizontalDemo, TabsDemo } from "~/components/output-area/testing";
import Leaderboard from "~/components/leaderboard/Leaderboard";
import QuestionArea from "~/components/question-area";

const HomePage = () => {
    return (

        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen items-start justify-center bg-[#3C3C3C]">
                <div className = "flex-col">
                    <OutputArea data={
                        "yeahgytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagytagyta sigma"
                    } />
                    <Leaderboard />
                </div>
                <div className="mt-4">
                    <QuestionArea />
                </div>
            </main>
        </>

    );
};

export default HomePage;
